name: create-coiled-datasets-m1
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - dask[complete]==2021.07.1
  - pyarrow
  - fastparquet
  - jupyterlab
  - dask-labextension
  - ipykernel
  - s3fs
  - coiled
  - lz4
  - numpy=1.21.1
