name: create-coiled-datasets
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - dask[complete]
  - pyarrow
  - jupyterlab
  - dask-labextension
  - ipykernel
  - s3fs
  - coiled
  - python-blosc
  - lz4


